CREATE DATABASE EMPRESA;
USE EMPRESA;
SELECT DATABASE();

CREATE TABLE Fornecimento (
    Quantidade INT,
    Fcodigo INT,
    PRcod INT,
    PRIMARY KEY (Fcodigo, PRcod),
    INDEX idx_qtd (Quantidade)
);

CREATE TABLE Instituicao (
    Icodigo INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Inome VARCHAR(100)
);

CREATE TABLE Fornecedor (
    Fcodigo INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Status VARCHAR(100) DEFAULT 'Ativo',
    Cidade VARCHAR(100),
    Fnome VARCHAR(100)
);

CREATE TABLE Projeto (
    PRcod INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PRnome VARCHAR(100),
    Cidade VARCHAR(100),
    Icodigo INT,
    INDEX idx_icodigo (Icodigo)
);

CREATE TABLE Peca (
    Pcodigo INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Pnome VARCHAR(100) NOT NULL,
    Cor VARCHAR(100) NOT NULL,
    Peso FLOAT NOT NULL,
    INDEX idx_pnome (Pnome)
);

ALTER TABLE Instituicao 
	RENAME TO Cidade, 
    CHANGE Icodigo Ccod INT AUTO_INCREMENT NOT NULL,
    CHANGE Inome Cnome VARCHAR(100) NOT NULL,
    ADD uf CHAR(2) NOT NULL,
    ADD INDEX idx_cnome (Cnome);

-- Mostrar tabelas no BD selecionado
SHOW TABLES;

ALTER TABLE FORNECEDOR
	ADD CONSTRAINT FK_CCOD_FORNECEDOR
    FOREIGN KEY (CCOD) REFERENCES CIDADE (CCOD);
    
SELECT * FROM CIDADE;
SELECT * FROM FORNECEDOR;
SELECT * FROM PECA;

-- Inserindo dados
INSERT INTO CIDADE
	VALUES ('1', 'Limeira', 'SP');
    
INSERT INTO CIDADE
	VALUES ('2', 'Matao', 'SP'),
    ('3', 'Campinas', 'SP'),
    ('4', 'Rio de Janeiro', 'RJ'),
    ('5', 'Belo Honrizonte', 'MG');
    
INSERT INTO FORNECEDOR
	VALUES('1', 'Ativo', 'LLC LOGISTICA', 'Limeira');
    
INSERT INTO FORNECEDOR
	VALUES('2', 'ATIVO', 'PRINCESA DO CAMPO', 'CAMPINAS'),
    ('3', 'ATIVO', 'DE LA PRA CA', 'BELO HORIZONTE'),
    ('4', 'ATIVO', 'FORNECIMENTOS BONS', 'MATAO');
    
INSERT INTO PECA
	VALUES(1 ,'LIMEIRA', 'PARAFUSO 1/2', 'PRATA', '1');
    
INSERT INTO PECA
	VALUES(2 ,'LIMEIRA', 'PARAFUSO 3/4', 'PRATA', '1.24'),
    (3, 'LIMEIRA', 'BUCHA', 'PRATA', '1.05');

SELECT * FROM PROJETO;

INSERT INTO PROJETO
	VALUES(1, 'PROJETO GK0', 'LIMEIRA', 1),
    (2, 'PROJETO ALMOX', 'PEDERNEIRAS', 2),
    (3, 'PROJETO EXT', 'LARANJAL PAULISTA', 3);