USE LIVRARIA;

SELECT *
FROM LIVROS
WHERE GENERO = "SUSPENSE";

SELECT TITULO, PRECO FROM LIVROS;

SELECT TITULO, AUTOR FROM LIVROS
WHERE QUANTIDADE > 10;

SELECT NOME, NACIONALIDADE, DATA_DE_NASCIMENTO FROM AUTORES
ORDER BY DATA_DE_NASCIMENTO DESC;

SELECT TITULO FROM LIVROS 
LIMIT 5;

SELECT NOME_EDITORA AS NOME, CONTATO AS EMAIL
FROM EDITORAS;

SELECT COUNT(*) AS TOTAL_LIVROS
FROM LIVROS;

SELECT FORMAT(AVG(PRECO), 2) AS TOTAL_LIVROS
FROM LIVROS;

SELECT SUM(PRECO) AS TOTAL_LIVROS
FROM LIVROS;

SELECT AUTOR, COUNT(*) AS QTTS
FROM LIVROS
GROUP BY AUTOR;

SELECT TITULO, PRECO FROM LIVROS
WHERE COD_LIVRO < 7 AND PRECO >10;

SELECT COD_LIVRO, COUNT(*) AS TOTAL_LIVROS
FROM LIVROS
GROUP BY COD_LIVRO
HAVING TOTAL_LIVROS > 5
ORDER BY TOTAL_LIVROS DESC;

SELECT TITULO, PRECO FROM LIVROS
WHERE TITULO LIKE "A%" AND PRECO > 10;

SELECT TITULO, PRECO FROM LIVROS
WHERE TITULO LIKE "%OS";

SELECT TITULO FROM LIVROS
WHERE TITULO LIKE '%S_L'
ORDER BY PRECO DESC;