CREATE DATABASE oficinaMecanica;
USE oficinaMecanica;

-- Tabela de Clientes
CREATE TABLE CLIENTES(
    CLIENTEID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CLIENTENOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100)
);

-- Tabela de Veículos
CREATE TABLE VEICULOS(
    VEICULOID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MARCA VARCHAR(100) NOT NULL,
    MODELO VARCHAR(255) NOT NULL,
    PLACA VARCHAR(7) NOT NULL UNIQUE,
    CLIENTEID INT NOT NULL,
    FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES(CLIENTEID),
    INDEX idx_placa (PLACA)
);

-- Tabela de Peças
CREATE TABLE PECAS(
    PECAID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PECANOME VARCHAR(255) NOT NULL,
    FABRICANTE VARCHAR(100),
    QTD_ESTOQUE INT NOT NULL DEFAULT 0,
    PRECO_CUSTO DECIMAL(10,2) NOT NULL,
    PRECO_VENDA DECIMAL(10,2) NOT NULL
);

-- Tabela de Mecânicos
CREATE TABLE MECANICOS(
    MECANICOID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MECANICONOME VARCHAR(255) NOT NULL,
    ESPECIALIDADE VARCHAR(150)
);

-- Tabela de Serviços
CREATE TABLE SERVICOS(
    SERVICOID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    SERVICONOME VARCHAR(255) NOT NULL,
    ESPECIALIDADE VARCHAR(150),
    PRECO_MAO_OBRA DECIMAL(10,2) NOT NULL
);

-- Tabela de Ordens de Serviço
CREATE TABLE ORDENS_SERVICO(
    ORDEMID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    VEICULOID INT NOT NULL,
    DATA_ABERTURA DATE NOT NULL,
    DATA_CONCLUSAO DATE,
    OS_STATUS VARCHAR(50) NOT NULL DEFAULT 'Em Execução',
    FOREIGN KEY (VEICULOID) REFERENCES VEICULOS(VEICULOID),
    INDEX idx_veiculoid (VEICULOID)
);

-- Tabela de relacionamento: Mecânicos que trabalharam em cada OS
CREATE TABLE OS_MECANICOS(
    ORDEMID INT NOT NULL,
    MECANICOID INT NOT NULL,
    PRIMARY KEY (ORDEMID, MECANICOID),
    FOREIGN KEY (ORDEMID) REFERENCES ORDENS_SERVICO(ORDEMID),
    FOREIGN KEY (MECANICOID) REFERENCES MECANICOS(MECANICOID)
);

-- Serviços realizados na ordem
CREATE TABLE OS_SERVICOS(
    ORDEMID INT NOT NULL,
    SERVICOID INT NOT NULL,
    PRECO_COBRADO DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ORDEMID, SERVICOID),
    FOREIGN KEY (ORDEMID) REFERENCES ORDENS_SERVICO(ORDEMID),
    FOREIGN KEY (SERVICOID) REFERENCES SERVICOS(SERVICOID)
);

-- Peças utilizadas na ordem
CREATE TABLE OS_PECAS(
    ORDEMID INT NOT NULL,
    PECAID INT NOT NULL,
    QUANTIDADE_USADA INT NOT NULL DEFAULT 1,
    PRECO_UNITARIO_COBRADO DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ORDEMID, PECAID),
    FOREIGN KEY (ORDEMID) REFERENCES ORDENS_SERVICO(ORDEMID),
    FOREIGN KEY (PECAID) REFERENCES PECAS(PECAID)
);

-- ============================================
-- INSERTS - DADOS DE EXEMPLO
-- ============================================

-- Inserindo Clientes
INSERT INTO CLIENTES (CLIENTENOME, EMAIL) VALUES
('Maria Silva', 'maria.silva@email.com'),
('João Santos', 'joao.santos@email.com'),
('Ana Costa', 'ana.costa@email.com'),
('Pedro Oliveira', 'pedro.oliveira@email.com'),
('Carla Souza', 'carla.souza@email.com'),
('Ricardo Almeida', 'ricardo.almeida@email.com'),
('Fernanda Lima', 'fernanda.lima@email.com'),
('Bruno Cardoso', 'bruno.cardoso@email.com'),
('Juliana Rocha', 'juliana.rocha@email.com'),
('Marcos Tavares', 'marcos.tavares@email.com');

-- Inserindo Veículos
INSERT INTO VEICULOS (MARCA, MODELO, PLACA, CLIENTEID) VALUES
('Honda', 'Civic', 'ABC1234', 1),
('Toyota', 'Corolla', 'DEF5678', 2),
('Fiat', 'Uno', 'GHI9012', 3),
('Chevrolet', 'S10', 'JKL3456', 4),
('Volkswagen', 'Gol', 'MNO7890', 5),
('Honda', 'City', 'PQR1122', 1),
('Ford', 'Ka', 'STU4567', 6),
('Ford', 'Fiesta', 'VWX8901', 7),
('Ford', 'Focus', 'YZA2345', 8),
('Ford', 'Ranger', 'BCD6789', 9),
('Ford', 'EcoSport', 'EFG0123', 10),
('Ford', 'Fusion', 'HIJ4567', 2),
('Hyundai', 'HB20', 'KLM8901', 6),
('Renault', 'Sandero', 'NOP2345', 7),
('Nissan', 'Kicks', 'QRS6789', 8),
('Jeep', 'Compass', 'TUV0123', 9),
('Chevrolet', 'Onix', 'WXY4567', 10),
('Volkswagen', 'Polo', 'ZAB8901', 3),
('Fiat', 'Argo', 'CDE2345', 4),
('Toyota', 'Hilux', 'FGH6789', 5);

-- Inserindo Peças
INSERT INTO PECAS (PECANOME, FABRICANTE, QTD_ESTOQUE, PRECO_CUSTO, PRECO_VENDA) VALUES
('Filtro de Óleo', 'Bosch', 50, 15.00, 25.00),
('Vela de Ignição', 'NGK', 100, 12.00, 20.00),
('Pastilha de Freio', 'Bosch', 30, 80.00, 120.00),
('Disco de Freio', 'TRW', 20, 150.00, 220.00),
('Correia Dentada', 'Gates', 15, 120.00, 180.00),
('Bateria 60Ah', 'Moura', 10, 300.00, 450.00),
('Óleo Motor 5W30', 'Castrol', 80, 35.00, 55.00),
('Amortecedor Dianteiro', 'Cofap', 12, 180.00, 280.00),
('Lâmpada H4', 'Philips', 60, 8.00, 15.00),
('Pneu 175/70 R14', 'Pirelli', 25, 220.00, 350.00),
('Filtro de Ar', 'Tecfil', 3, 25.00, 40.00),
('Filtro de Combustível', 'Bosch', 2, 30.00, 50.00),
('Junta do Cabeçote', 'Elring', 8, 250.00, 380.00),
('Bomba de Água', 'Nakata', 6, 120.00, 200.00),
('Radiador', 'Visconde', 4, 280.00, 450.00);

-- Inserindo Mecânicos
INSERT INTO MECANICOS (MECANICONOME, ESPECIALIDADE) VALUES
('Roberto Ferreira', 'Motor'),
('Carlos Mendes', 'Injeção Eletrônica'),
('José Ricardo', 'Suspensão'),
('Paulo Henrique', 'Freios'),
('Anderson Silva', 'Motor'),
('Marcelo Costa', 'Injeção Eletrônica');

-- Inserindo Serviços
INSERT INTO SERVICOS (SERVICONOME, ESPECIALIDADE, PRECO_MAO_OBRA) VALUES
('Troca de Óleo', 'Motor', 80.00),
('Revisão Completa', 'Geral', 250.00),
('Troca de Freios', 'Freios', 150.00),
('Alinhamento e Balanceamento', 'Suspensão', 120.00),
('Troca de Correia Dentada', 'Motor', 200.00),
('Diagnóstico Eletrônico', 'Injeção Eletrônica', 180.00),
('Troca de Bateria', 'Elétrica', 50.00),
('Reparo de Suspensão', 'Suspensão', 300.00),
('Sistema Elétrico', 'Elétrica', 220.00),
('Troca de Embreagem', 'Motor', 450.00);

-- Inserindo Ordens de Serviço
INSERT INTO ORDENS_SERVICO (VEICULOID, DATA_ABERTURA, DATA_CONCLUSAO, OS_STATUS) VALUES
(1, '2024-11-15', '2024-11-16', 'Concluído'),
(2, '2024-11-18', '2024-11-20', 'Concluído'),
(3, '2024-11-20', '2024-11-22', 'Concluído'),
(4, '2024-11-22', '2024-11-25', 'Concluído'),
(5, '2024-11-25', NULL, 'Aguardando Peça'),
(6, '2024-11-28', '2024-11-30', 'Concluído'),
(7, '2025-06-10', '2025-06-12', 'Concluído'),
(8, '2025-07-15', NULL, 'Em Execução'),
(9, '2025-08-20', '2025-08-22', 'Concluído'),
(10, '2025-09-05', NULL, 'Em Execução'),
(1, '2025-10-10', '2025-10-12', 'Concluído'),
(2, '2025-11-01', NULL, 'Aguardando Peça'),
(7, '2025-11-15', '2025-11-17', 'Concluído');

-- Inserindo relacionamento OS_MECANICOS
INSERT INTO OS_MECANICOS (ORDEMID, MECANICOID) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 1),
(4, 4),
(5, 4),
(6, 2),
(7, 3),
(8, 2),
(9, 1),
(10, 5),
(11, 2),
(12, 4),
(13, 3);

-- Relacionando Serviços com Ordens
INSERT INTO OS_SERVICOS (ORDEMID, SERVICOID, PRECO_COBRADO) VALUES
(1, 1, 80.00),
(1, 4, 120.00),
(2, 2, 250.00),
(3, 3, 150.00),
(4, 5, 200.00),
(4, 2, 250.00),
(5, 7, 50.00),
(6, 1, 80.00),
(6, 8, 300.00),
(7, 4, 120.00),
(8, 6, 180.00),
(9, 1, 80.00),
(10, 3, 150.00),
(11, 2, 250.00),
(12, 7, 50.00),
(13, 8, 300.00);

-- Relacionando Peças com Ordens
INSERT INTO OS_PECAS (ORDEMID, PECAID, QUANTIDADE_USADA, PRECO_UNITARIO_COBRADO) VALUES
(1, 1, 1, 25.00),
(1, 7, 4, 55.00),
(2, 1, 1, 25.00),
(2, 2, 4, 20.00),
(2, 7, 4, 55.00),
(3, 3, 4, 120.00),
(3, 4, 2, 220.00),
(4, 5, 1, 180.00),
(5, 6, 1, 450.00),
(6, 1, 1, 25.00),
(6, 7, 4, 55.00),
(6, 8, 2, 280.00),
(7, 10, 4, 350.00),
(8, 11, 1, 40.00),
(9, 1, 1, 25.00),
(9, 7, 4, 55.00),
(10, 3, 4, 120.00),
(11, 2, 4, 20.00),
(12, 6, 1, 450.00),
(13, 8, 2, 280.00);


-- Somativa 2
SELECT * FROM veiculos WHERE VEICULONOME = "Ford";

SELECT * FROM ordens_servico WHERE ORDEMDATA < '2025-06-01';
SELECT * FROM mecanicos WHERE ESPECIALIDADE = "Injeção Eletrônica";
SELECT * FROM orders_servico WHERE OS_STATUS = "Aguardando peça";
SELECT * FROM PECAS WHERE QTD_ESTOQUE < 5;

SELECT V.VEICULOID, V.MARCA, V.MODELO, V.PLACA
FROM VEICULOS V
WHERE (
    SELECT COUNT(*)
    FROM ORDENS_SERVICO OS
    WHERE OS.VEICULOID = V.VEICULOID
) > 1;

SELECT 
    OSM.ORDEMID,
    M.MECANICONOME
FROM OS_MECANICOS OSM
INNER JOIN MECANICOS M ON OSM.MECANICOID = M.MECANICOID
WHERE OSM.MECANICOID = 3;

SELECT PECANOME, PRECO_VENDA FROM PECAS WHERE PRECO_VENDA > 200;

-- UPDATE

UPDATE PECAS
SET PRECO_VENDA = PRECO_VENDA * 1.05
WHERE FABRICANTE = "Bosch";

UPDATE ORDENS_SERVICO
SET OS_STATUS = "Concluído"
WHERE ORDEMID = 10;

UPDATE ORDENS_SERVICO
SET DATA_ABERTURA = '2025-10-10'
WHERE OS_STATUS = 'Em Execução';

UPDATE PECAS
SET QTD_ESTOQUE = QTD_ESTOQUE * 2
WHERE PECAID = 20;

-- ALTER TABLE

ALTER TABLE CLIENTES
ADD COLUMN EMAIL VARCHAR(100);

ALTER TABLE MECANICOS
MODIFY COLUMN ESPECIALIDADE VARCHAR(100);

ALTER TABLE ORDENS_SERVICO
DROP COLUMN DIAGNOSTICO_ENTRADA;

ALTER TABLE PECAS
ADD CONSTRAINT chk_preco_venda CHECK (PRECO_VENDA >= PRECO_CUSTO);

-- JOIN
SELECT 
    OS.ORDEMID,
    C.CLIENTENOME,
    V.PLACA,
    OS.DATA_ABERTURA,
    OS.STATUS
FROM ORDENS_SERVICO OS
INNER JOIN VEICULOS V ON OS.VEICULOID = V.VEICULOID
INNER JOIN CLIENTES C ON V.CLIENTEID = C.CLIENTEID;

SELECT
    OS.ORDEMID,
    PC.PECAID,
    PC.PECANOME,
    OP.QUANTIDADE_USADA,
    OP.PRECO_UNITARIO_COBRADO
FROM ORDENS_SERVICO OS
INNER JOIN OS_PECAS OP ON OS.ORDEMID = OP.ORDEMID
INNER JOIN PECAS PC ON OP.PECAID = PC.PECAID
WHERE OS.ORDEMID = 5;

SELECT 
    M.MECANICOID,
    M.MECANICONOME,
    M.ESPECIALIDADE
FROM OS_MECANICOS OSM
INNER JOIN MECANICOS M ON OSM.MECANICOID = M.MECANICOID
WHERE OSM.ORDEMID = 7;

SELECT
    V.VEICULOID,
    V.MARCA,
    V.MODELO,
    V.PLACA,
    C.CLIENTENOME
FROM VEICULOS V
INNER JOIN CLIENTES C ON V.CLIENTEID = C.CLIENTEID;
    
    
-- INNER JOIN
SELECT 
    V.PLACA,
    V.MODELO,
    V.MARCA,
    OS.ORDEMID,
    OS.DATA_ABERTURA
FROM VEICULOS V
INNER JOIN ORDENS_SERVICO OS ON V.VEICULOID = OS.VEICULOID
WHERE OS.STATUS = 'Em Execução';

SELECT
    C.CLIENTEID,
    C.CLIENTENOME,
    C.EMAIL
FROM CLIENTES C
INNER JOIN VEICULOS V ON C.CLIENTEID = V.CLIENTEID
WHERE V.MARCA = 'Volkswagen';

SELECT
    M.MECANICOID,
    M.MECANICONOME,
    M.ESPECIALIDADE
FROM MECANICOS M
INNER JOIN OS_MECANICOS OSM ON M.MECANICOID = OSM.MECANICOID;

SELECT
    OS.ORDEMID,
    SS.SERVICOID,
    S.SERVICONOME,
    OS.STATUS,
    OS.DATA_ABERTURA
FROM OS_SERVICOS SS
INNER JOIN ORDENS_SERVICO OS ON SS.ORDEMID = OS.ORDEMID
INNER JOIN SERVICOS S ON SS.SERVICOID = S.SERVICOID
WHERE OS.STATUS = 'Em Execução';

-- LEFT JOIN
SELECT 
    C.CLIENTEID,
    C.CLIENTENOME,
    C.EMAIL,
    OS.ORDEMID,
    OS.DATA_ABERTURA,
    OS.STATUS
FROM CLIENTES C
LEFT JOIN VEICULOS V ON C.CLIENTEID = V.CLIENTEID
LEFT JOIN ORDENS_SERVICO OS ON V.VEICULOID = OS.VEICULOID
ORDER BY C.CLIENTEID, OS.DATA_ABERTURA;

SELECT 
    M.MECANICOID,
    M.MECANICONOME,
    M.ESPECIALIDADE,
    COUNT(OSM.ORDEMID) AS TOTAL_OS
FROM MECANICOS M
LEFT JOIN OS_MECANICOS OSM ON M.MECANICOID = OSM.MECANICOID
GROUP BY M.MECANICOID, M.MECANICONOME, M.ESPECIALIDADE;

SELECT 
    P.PECANOME,
    SUM(OSP.QUANTIDADE_USADA) AS TOTAL_VENDIDO
FROM PECAS P
LEFT JOIN OS_PECAS OSP ON P.PECAID = OSP.PECAID
GROUP BY P.PECAID, P.PECANOME;

SELECT
	V.MARCA,
    OS.DATA_ABERTURA
FROM VEICULOS V
LEFT JOIN ORDENS_SERVICO OS ON V.VEICULOID = OS.VEICULOID
GROUP BY V.VEICULOID, V.MARCA, OS.DATA_ABERTURA;

-- RIGHT JOIN

SELECT 
    OS.ORDEMID,
    OS.DATA_ABERTURA,
    OS.STATUS,
    C.CLIENTENOME,
    V.PLACA
FROM ORDENS_SERVICO OS
INNER JOIN VEICULOS V ON OS.VEICULOID = V.VEICULOID
RIGHT JOIN CLIENTES C ON V.CLIENTEID = C.CLIENTEID;

SELECT 
    S.SERVICOID,
    S.SERVICONOME,
    S.ESPECIALIDADE,
    S.PRECO_MAO_OBRA,
    OSS.ORDEMID
FROM SERVICOS S
LEFT JOIN OS_SERVICOS OSS ON S.SERVICOID = OSS.SERVICOID
ORDER BY S.SERVICOID;

SELECT 
    OSM.ORDEMID,
    OSM.MECANICOID,
    M.MECANICONOME,
    M.ESPECIALIDADE
FROM OS_MECANICOS OSM
RIGHT JOIN MECANICOS M ON OSM.MECANICOID = M.MECANICOID;

-- Com RIGHT JOIN (veículos à direita):
SELECT 
    OS.ORDEMID,
    C.CLIENTENOME
FROM ORDENS_SERVICO OS
RIGHT JOIN VEICULOS V ON OS.VEICULOID = V.VEICULOID
RIGHT JOIN CLIENTES C ON V.CLIENTEID = C.CLIENTEID;

SELECT 
    S.SERVICONOME,
    OSS.ORDEMID
FROM OS_SERVICOS OSS
RIGHT JOIN SERVICOS S ON OSS.SERVICOID = S.SERVICOID;

SELECT 
    OSM.ORDEMID,
    M.MECANICONOME
FROM OS_MECANICOS OSM
RIGHT JOIN MECANICOS M ON OSM.MECANICOID = M.MECANICOID;

SELECT 
    V.PLACA,
    V.MODELO,
    OS.ORDEMID
FROM ORDENS_SERVICO OS
RIGHT JOIN VEICULOS V ON OS.VEICULOID = V.VEICULOID;

-- SUBCONSULTAS

SELECT C.CLIENTENOME
FROM CLIENTES C
WHERE C.CLIENTEID IN (
    SELECT V.CLIENTEID
    FROM VEICULOS V
    INNER JOIN ORDENS_SERVICO OS ON V.VEICULOID = OS.VEICULOID
    GROUP BY V.CLIENTEID
    HAVING COUNT(*) > 3
);

SELECT P.PECANOME
FROM PECAS P
INNER JOIN OS_PECAS OSP ON P.PECAID = OSP.PECAID
WHERE OSP.ORDEMID IN (
    SELECT ORDEMID
    FROM OS_MECANICOS
    WHERE MECANICOID = 4
);

SELECT V.PLACA, V.MODELO
FROM VEICULOS V
WHERE V.VEICULOID NOT IN (
    SELECT VEICULOID
    FROM ORDENS_SERVICO
);

SELECT 
    SERVICONOME,
    PRECO_MAO_OBRA
FROM SERVICOS
WHERE PRECO_MAO_OBRA > (
    SELECT AVG(PRECO_MAO_OBRA)
    FROM SERVICOS
);

