-- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS ofc_Mecanica;
USE ofc_Mecanica;

-- Tabela de Clientes
CREATE TABLE CLIENTES(
    CLIENTEID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CLIENTENOME VARCHAR(255) NOT NULL
);

-- Tabela de Veículos
CREATE TABLE VEICULOS(
    VEICULOID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    VEICULONOME VARCHAR(255) NOT NULL,
    VEICULOTIPO VARCHAR(255),
    VEICULOPLACA VARCHAR(7) NOT NULL,
    CLIENTEID INT NOT NULL,
    FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES(CLIENTEID)
);

-- Tabela de Peças
CREATE TABLE PECAS(
    PECAID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PECANOME VARCHAR(255) NOT NULL,
    PECAQTT INT NOT NULL DEFAULT 0
);

-- Tabela de Mecânicos
CREATE TABLE MECANICOS(
    MECANICOID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MECANICONOME VARCHAR(255) NOT NULL
);

-- Tabela de Serviços
CREATE TABLE SERVICOS(
    SERVICOID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    SERVICONOME VARCHAR(255) NOT NULL
);

-- Tabela de Ordens de Serviço
CREATE TABLE ORDENS_SERVICO(
    ORDEMID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    VEICULOID INT NOT NULL,
    MECANICOID INT NOT NULL,
    ORDEMDATA DATE NOT NULL,
    FOREIGN KEY (VEICULOID) REFERENCES VEICULOS(VEICULOID),
    FOREIGN KEY (MECANICOID) REFERENCES MECANICOS(MECANICOID)
);

-- Serviços realizados na ordem
CREATE TABLE ORDEM_SERVICOS(
    ORDEMID INT NOT NULL,
    SERVICOID INT NOT NULL,
    PRIMARY KEY (ORDEMID, SERVICOID),
    FOREIGN KEY (ORDEMID) REFERENCES ORDENS_SERVICO(ORDEMID),
    FOREIGN KEY (SERVICOID) REFERENCES SERVICOS(SERVICOID)
);

-- Peças utilizadas na ordem
CREATE TABLE ORDEM_PECAS(
    ORDEMID INT NOT NULL,
    PECAID INT NOT NULL,
    QUANTIDADE INT NOT NULL DEFAULT 1,
    PRIMARY KEY (ORDEMID, PECAID),
    FOREIGN KEY (ORDEMID) REFERENCES ORDENS_SERVICO(ORDEMID),
    FOREIGN KEY (PECAID) REFERENCES PECAS(PECAID)
);