CREATE DATABASE LIMPEZADB;

USE LIMPEZADB;

CREATE TABLE PRODUTOS(
	PROD_COD INT,
    PROD_NOME VARCHAR(255),
    PROD_VALIDADE DATE,
    PROD_VALOR FLOAT,
    PROD_VOLUME FLOAT
);

CREATE TABLE MANUTENCAO(
	SERV_COD INT,
    SERV_RESPONSAVEL VARCHAR(100),
	SERV_TIPO VARCHAR(20),
    SERV_DATA_INICIO DATETIME,
    SERV_DATA_FIM DATETIME
);

CREATE TABLE VENDAS(
	VEND_COD INT,
    VEND_VENDEDOR VARCHAR(100),
    VEND_DATA DATETIME,
    VEND_VALOR FLOAT,
    VEND_PRODUTOS VARCHAR(255)
);

CREATE TABLE CLIENTES(
	CLIENTES_COD INT,
    CLIENTES_NOME VARCHAR(100),
    CLIENTES_TELEFONE VARCHAR(16),
    CLIENTES_CPF VARCHAR(14),
    CLIENTES_NOME VARCHAR(100)
);

CREATE TABLE FUNCIONARIO(
	FUNC_COD INT,
    FUNC_NOME VARCHAR(100),
    FUNC_RE INT,
    FUNC_DATA_NASCIMENTO DATE,
    FUNC_EMAIL VARCHAR(255)
);