CREATE DATABASE CRUD;
USE CRUD;
SET SQL_SAFE_UPDATES = 0;

CREATE TABLE CURSOS(
	ID_CURSOS INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TITULO VARCHAR(255),
    DESCRICAO TEXT,
    CARGA_HORARIO INT,
    CURSOS_STATUS VARCHAR(255) DEFAULT 'INATIVO'
);

CREATE TABLE ALUNOS(
	ID_ALUNOS INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DATA_NASCIMENTO DATE,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE INSCRICOES(
	ID_INSCRICOES INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FK_ID_ALUNOS INT,
    FK_ID_CURSOS INT,
    DATA_INSCRICAO DATE,
    FOREIGN KEY(FK_ID_ALUNOS) REFERENCES ALUNOS(ID_ALUNOS),
    FOREIGN KEY(FK_ID_CURSOS) REFERENCES CURSOS(ID_CURSOS)
);

CREATE TABLE AVALIACOES(
	ID_AVALIACOES INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOTA DECIMAL(3,1),
    COMENTARIO TEXT,
    FK_ID_INSCRICOES INT,
    FOREIGN KEY(FK_ID_INSCRICOES) REFERENCES INSCRICOES(ID_INSCRICOES)
);

INSERT INTO CURSOS (TITULO, DESCRICAO, CARGA_HORARIO, CURSOS_STATUS) VALUES
('Introdução ao SQL', 'Curso básico sobre SQL e bancos de dados relacionais.', 40, 'ATIVO'),
('Java para Iniciantes', 'Curso introdutório à linguagem Java.', 60, 'ATIVO'),
('Desenvolvimento Web', 'Curso de HTML, CSS e JavaScript.', 80, 'ATIVO'),
('Linux Essentials', 'Fundamentos do sistema operacional Linux.', 50, 'ATIVO');

-- Inserindo 5 alunos
INSERT INTO ALUNOS (DATA_NASCIMENTO, NOME, EMAIL) VALUES
('2000-05-15', 'Ana Silva', 'ana.silva@email.com'),
('1998-09-22', 'Bruno Costa', 'bruno.costa@email.com'),
('2002-12-03', 'Carla Souza', 'carla.souza@email.com'),
('1999-07-18', 'Diego Ramos', 'diego.ramos@email.com'),
('2001-03-27', 'Fernanda Lima', 'fernanda.lima@email.com');

INSERT INTO CURSOS (TITULO, DESCRICAO, CARGA_HORARIO) VALUES
	('Machine Learning', 'Conceitos iniciais de aprendizado de máquina.', 100);

-- Inserindo 5 inscrições (cada aluno em um curso)
INSERT INTO INSCRICOES (FK_ID_ALUNOS, FK_ID_CURSOS, DATA_INSCRICAO) VALUES
(1, 1, '2025-01-10'),
(2, 2, '2025-01-12'),
(3, 3, '2025-01-15'),
(4, 4, '2025-01-18'),
(5, 5, '2025-01-20');

-- Inserindo 3 avaliações (ligadas às inscrições)
INSERT INTO AVALIACOES (NOTA, COMENTARIO, FK_ID_INSCRICOES) VALUES
(9.5, 'Respostas corretas e objetivas, muito bem!', 1),
(8.0, 'Respostas boas que atingiram bem o conteúdo', 2),
(6.5, 'Respostas que atingiram o conteúdo de forma parcial', 3);

UPDATE ALUNOS
	SET EMAIL = "brunoc.silva@gmail.com",
    NOME = "Bruno Costa da Silva"
    WHERE ID_ALUNOS = 2;
    
UPDATE CURSOS
	SET CARGA_HORARIO = 120,
    CURSOS_STATUS = 'ATIVO'
    WHERE ID_CURSOS = 5;

UPDATE AVALIACOES
	SET NOTA = 10
    WHERE ID_AVALIACOES = 5;

DELETE FROM INSCRICOES
	WHERE ID_INSCRICOES = 3;
    
DELETE FROM CURSOS
	WHERE ID_CURSOS = 3;

INSERT INTO AVALIACOES (NOTA, COMENTARIO, FK_ID_INSCRICOES) VALUES
 (3.2, 'Muito ruim, %$&*¨#@', 4);
 
 DELETE FROM AVALIACOES
	WHERE NOTA = 3.2;

DELETE FROM ALUNOS
	WHERE NOME = "Diego Ramos";
    
SELECT * FROM ALUNOS;
SELECT NOME, EMAIL FROM ALUNOS;
SELECT * FROM CURSOS WHERE CARGA_HORARIO > 30;
SELECT * FROM CURSOS WHERE STATUS_CURSO = 'INATIVO';
SELECT * FROM ALUNOS WHERE ANO_DE_NASCIMENTO > '1995-01-01';
SELECT * FROM AVALIACOES WHERE NOTA > 9;

SELECT COUNT(*) AS TOTAL_LINHAS
	FROM CURSOS;
    
SELECT TITULO, CARGA_HORARIO
FROM CURSOS
ORDER BY CARGA_HORARIO DESC
LIMIT 3;