-- CRIAÇÃO DE BANCO DE DADOS
CREATE DATABASE TRANSPORTEDB;

-- ATIVAR BANCO DE DADOS
USE TRANSPORTEDB;

-- CRIAR TABELAS
CREATE TABLE VEICULOS(
	COD_VEICULO INT,
    PLACA_VEICULO VARCHAR(10),
    FABRICANTE VARCHAR(100),
	DISPONIBILIDADE VARCHAR(20),
    KILOMETRAGEM FLOAT
);

CREATE TABLE REBOQUE(
	COD_REBOQUE INT,
    TIPO VARCHAR(20),
    NUM_EIXOS INT,
	DISPONIBILIDADE VARCHAR(20),
    TAMANHO FLOAT
);

CREATE TABLE ENTREGA(
	COD_ENTREGA INT,
    CARGA VARCHAR(100),
    TEMPO_LIMITE TIME,
    LOCAL_INICIO VARCHAR(255),
	LOCAL_FIM VARCHAR(255)
);

CREATE TABLE MOTORISTA(
	COD_MOTORISTA INT,
    NOME_MOTORISTA VARCHAR(100),
    CPF VARCHAR(14),
	CERTIFICADOS TEXT,
    DATA_NASCIMENTO DATE
);

CREATE TABLE GARAGEM(
	COD_GARAGEM INT,
    LOCAL_GARAGEM VARCHAR(255),
    QTT_VAGAS INT,
    QTT_REBOQUES INT,
    QTT_VEICULOS INT
);