-- CRIAR BANCO DE DADOS --
CREATE DATABASE EXEMPLO2;

-- ATIVAR BANCO DE DADOS --
USE EXEMPLO2;

-- CRIAR TABELA --

CREATE TABLE CLIENTE(
	COD_CLIENTE INT,
    NOME_CLIENTE VARCHAR(100),
    CPF_CLIENTE VARCHAR(14),
    CELULAR VARCHAR(16),
    ENDERECO VARCHAR(255)
);

CREATE TABLE PRODUTO(
	COD_PRODUTO INT,
    NOME_PRODUTO VARCHAR(50),
    DESCRICAO TEXT,
    VALOR FLOAT,
    QTDE INT
);

CREATE TABLE ESTOQUE(
	COD_ESTOQUE INT,
    NOME_PRODUTO VARCHAR(255),
    QTDE INT,
    POSICAO VARCHAR(10),
    VALIDADE DATE
);

CREATE TABLE FUNCIONARIO(
	COD_FUNCIONARIO INT,
    NOME_FUNCIONARIO VARCHAR(100),
    SALARIO FLOAT,
    DATA_NASCIMENTO DATE,
    CPF_FUNCIONARIO VARCHAR(14)
);

-- CONSULTA DE TABELAS

SELECT * FROM CLIENTE;