CREATE DATABASE EXEMPLO3;

USE EXEMPLO3;
CREATE TABLE IF NOT EXISTS CLIENTES (
	COD_CLIENTE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	NOME_CLIENTE VARCHAR(100) NOT NULL,
	CPF_CLIENTE VARCHAR(14) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
	ESTADO CHAR(2) DEFAULT 'SP',
	CELULAR VARCHAR(19) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
	COD_PRODUTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    QTDE INT NOT NULL,
    VALOR DECIMAL(5,2) NOT NULL,
    DESCRICAO TEXT
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
	COD_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME_FORCENEDOR VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    CELULAR VARCHAR(19) NOT NULL,
    ENDERECO VARCHAR(255)
);

CREATE TABLE TEM (
	COD_TEM INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    COD_FORNECEDOR INT,
    COD_PRODUTO INT,
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTOS (COD_PRODUTO),
    FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDORES (COD_FORNECEDOR)
);

-- CONSULTA DE TABELAS
SELECT * FROM CLIENTES;

-- REMOÇÃO DE TABELAS
DROP TABLE CLIENTES;

-- REMOÇÃO DE BANCO DE DADOS
DROP DATABASE EXEMPLO3;

-- ALTERAÇÕES DE CAMPOS
ALTER TABLE CLIENTES
ADD SEXO CHAR(1);

ALTER TABLE CLIENTES
DROP COLUMN SEXO;

ALTER TABLE CLIENTES
RENAME TO PESSOA_FISICA;

ALTER TABLE PESSOA_FISICA
CHANGE CPF CPFP INT;

ALTER TABLE PESSOA_FISICA
MODIFY COLUMN NOME_CLIENTE VARCHAR(150);

ALTER TABLE PESSOA_FISICA
MODIFY COLUMN ESTADO CHAR(2) DEFAULT 'MG';

-- REVISAR ALTERAÇÕES

-- ACRESCENTAR OS CAMPOS CIDADE EM CLIENTES
ALTER TABLE PESSOA_FISICA
RENAME CLIENTES;

ALTER TABLE CLIENTES
ADD CIDADE VARCHAR(50);

-- ALTERAR O CAMPO VALOR PRODUTOS PARA DECIMAL (7,2)
ALTER TABLE PRODUTOS
MODIFY COLUMN VALOR DECIMAL(7,2);

-- ACRESCENTAR O CAMPO CIDADE E ESTADO EM FORNECEDOR E DEFINIR O ESTADO COMO PADRÃO 'SP'
ALTER TABLE FORNECEDORES
ADD CIDADE VARCHAR(40);

ALTER TABLE FORNECEDORES
ADD ESTADO CHAR(2) DEFAULT 'SP';


