CREATE DATABASE DB_JOINS;
USE DB_JOINS;

CREATE TABLE cliente (
	CODCLI CHAR(3) NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP CHAR(9) NOT NULL
);

CREATE TABLE venda (
	DUPLIC CHAR(6) NOT NULL PRIMARY KEY,
    VALOR DECIMAL(10,2) NOT NULL,
    VENCTO DATE NOT NULL,
    CODCLI CHAR(3) NOT NULL,
    FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI)
);

INSERT INTO CLIENTE VALUES (
	'250',
    'BANCO BARCA S/A',
    'R. VITO, 34',
    'SAO SEBASTIAO',
    'CE',
    '62380-000'
);

INSERT INTO CLIENTE VALUES (
	'820',
    'MECANICA SAO PAULO',
    'R. DO MACUCO, 99',
    'SANTO ANTONIO',
    'ES',
    '29810-020'
);

INSERT INTO CLIENTE VALUES (
	'170',
    'POSTO BRASIL LTDA.',
    'AV. IMPERIO, 85', 
    'GUAGIRUS', 
    'BA', 
    '42837-000'
);

INSERT INTO VENDA VALUES (
	'230001',
    1300.00,
    '2001-06-10',
    '250'
);
    
INSERT INTO VENDA VALUES (
    '230099',
    1000.00,
    '2002-10-02',
    '170'
);
    
INSERT INTO VENDA VALUES (
    '997818',
    3000.00,
    '2001-11-11',
    '820'
);

-- CONSULTAS (JUNÇÕES - JOIN) 
SELECT venda.DUPLIC, cliente.NOME
FROM cliente, venda
WHERE cliente.CODCLI = venda.CODCLI;

-- COM INNER JOIN
SELECT venda.DUPLIC, cliente.NOME
FROM cliente INNER JOIN venda ON cliente.CODCLI = venda.CODCLI;

-- COM ALIAS
SELECT ven.DUPLIC, cli.NOME
FROM CLIENTE cli INNER JOIN venda ven ON cli.CODCLI = ven.CODCLI;

-- COM ORDER BY
SELECT ven.DUPLIC, cli.NOME
FROM cliente cli INNER JOIN venda ven ON cli.CODCLI = ven.CODCLI
ORDER BY cli.NOME;

-- COM LEFT JOIN
SELECT ven.DUPLIC, cli.NOME
FROM cliente cli LEFT JOIN venda ven ON cli.CODCLI = ven.CODCLI
ORDER BY cli.NOME;

-- RIGHT JOIN
SELECT ven.DUPLIC, cli.NOME, cli.CIDADE
FROM cliente cli RIGHT JOIN venda ven ON cli.CODCLI = ven.CODCLI
ORDER BY cli.NOME;

-- QUANTIDADE
SELECT cliente.NOME, COUNT(*) AS QTDE
FROM cliente INNER JOIN venda ON cliente.CODCLI = venda.CODCLI
GROUP BY cliente.NOME;

-- SOMA
SELECT cliente.NOME, SUM(VALOR) AS TOTAL
FROM CLIENTE INNER JOIN VENDA ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY CLIENTE.NOME;