CREATE DATABASE JOINS;
USE JOINS;

CREATE TABLE TabelaEX (
	NOME VARCHAR(100)
);

CREATE TABLE TabelaFX (
	NOME VARCHAR(100)
);

-- INSERIR DADOS

INSERT INTO TabelaEX (NOME) VALUES
	('Cláudia'),
    ('Cadu'),
    ('Bruno'),
    ('Lucineia'),
    ('Augusto');

INSERT INTO TabelaFX (NOME) VALUES
	('Amarildo'),
    ('Alvaro'),
    ('Bruno'),
    ('Damares'),
    ('Augusto');

-- INNER JOIN
SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
INNER JOIN TABELAFX AS FX
ON EX.NOME = FX.NOME;

-- LEFT JOIN
SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
LEFT JOIN TABELAFX AS FX
ON EX.NOME = FX.NOME;

-- RIGHT JOIN
SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
RIGHT JOIN TABELAFX AS FX
ON EX.NOME = FX.NOME;

-- LEFT JOIN COM NULL
SELECT EX.NOME, FX.NOME
FROM TABELAEX AS EX
LEFT JOIN TABELAFX AS FX
ON EX.NOME = FX.NOME
WHERE FX.NOME IS NULL;