-- CRIAR BANCO DE DADOS
CREATE DATABASE PIZZADB;

-- ATIVAR BANCO DE DADOS
USE PIZZADB;

-- CRIAR TABELAS
CREATE TABLE CLIENTES(
	ID_CLIENTE INT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(20),
    CPF VARCHAR(14),
    ENDERECO VARCHAR(100)
);

CREATE TABLE FUNCIONARIOS(
	ID_FUNCIONARIO INT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(20),
    SETOR VARCHAR(20),
    FUNCAO VARCHAR(20),
    SALARIO INT
);

CREATE TABLE PRODUTOS(
	ID_PRODUTOS INT PRIMARY KEY,
    NOME_PRODUTOS VARCHAR(100),
    TIPO VARCHAR(10),
    DESCRICAO VARCHAR(200),
    ATRIBUTOS VARCHAR(20)
);

CREATE TABLE INGREDIENTES(
	ID_INGREDIENTES INT PRIMARY KEY,
    NOME_ING VARCHAR(20),
    DESC_ING VARCHAR(100),
    QTT_ING INT,
    UNIDADE_MEDIDA VARCHAR(4),
    DATA_VALIDADE DATE
);



SELECT * FROM PRODUTOS;