-- CRIAR BANCO DE DADOS --
CREATE DATABASE ESCOLA; 

-- ATIVAR BANCO --
USE ESCOLA;

-- CRIAR TABELA --
CREATE TABLE ALUNO (
	ID_ALUNO INT,
	NOME_ALUNO VARCHAR(100),
    ENDERECO VARCHAR(100),
    CPF VARCHAR(14),
    DATA_NASCIMENTO DATE
);

CREATE TABLE CURSO (
	ID_CURSO INT PRIMARY KEY,
	NOME_CURSO VARCHAR(100),
    DATA_INICIO DATE,    
    DATA_TERMINO DATE
);

CREATE TABLE PROFESSOR (
	ID_PROFESSOR INT PRIMARY KEY,
	NOME_PROFESSOR VARCHAR(100),
    DATA_NASCIMENTO DATE,
    AREA_ATUACAO VARCHAR(100),
    SALARIO INT
);