CREATE DATABASE REMOTEC;
USE REMOTEC;
SELECT DATABASE();

CREATE TABLE PRODUTO (
	CODIGO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    UNIDADE CHAR(3) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    VALOR_UNIT DECIMAL(7,2) NOT NULL
);

CREATE TABLE VENDEDOR(
	CODIGO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    SALARIO DECIMAL(7,2) NOT NULL,
    FSALARIAL CHAR(1) NOT NULL,
    PRIMARY KEY(CODIGO)
);

INSERT INTO PRODUTO (UNIDADE, DESCRICAO, VALOR_UNIT)
	VALUES ('PEC', 'TECLADO MECANICO RAZOR 123321', 3500),
    ('PEC', 'MOUSE GAMER COM BOTOES NO LADO 122311', 750),
    ('PEC', 'PLACA DE VIDEO GTX 1650 TI 982332', 2500);

INSERT INTO VENDEDOR (NOME, SALARIO, FSALARIAL)
	VALUES ('KAYQUE', '2000', '1'),
    ('JOAO', '2500', '2'),
    ('BRUNO', '3000', '3'),
    ('CARLOS', '4500', '4');

UPDATE PRODUTO
SET VALOR_UNIT = 32.00
WHERE DESCRICAO = 'TECLADO MECANICO RAZOR 123321';

SELECT * FROM PRODUTO;

UPDATE PRODUTO
	SET VALOR_UNIT = 28.00,
	DESCRICAO = 'MOUSE GAMER COM BOTOES NO LADO 122311'
	WHERE CODIGO = 2;

UPDATE VENDEDOR
	SET SALARIO = 3150
	WHERE FSALARIAL = 1;

UPDATE VENDEDOR
	SET SALARIO = SALARIO + (SALARIO * 0.1)
	WHERE FSALARIAL = 2;

UPDATE VENDEDOR
	SET SALARIO = 3500
    WHERE FSALARIAL = 3;

DELETE FROM VENDEDOR
WHERE SALARIO < 3000;

SELECT * FROM VENDEDOR;

DELETE FROM VENDEDOR WHERE FSALARIAL>= 1 AND CODIGO<=2;

-- ESVAZIANDO A TABELA

DELETE FROM CLIENTES;

TRUNCATE TABLE PRODUTO;