CREATE DATABASE RESERVADB;
USE RESERVADB;

CREATE TABLE USUARIO(
	COD_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE VARCHAR(20)
);

CREATE TABLE RESERVA (
	COD_RESERVA INT PRIMARY KEY AUTO_INCREMENT,
	DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS_RESERVA VARCHAR(10)
);

CREATE TABLE EQUIPAMENTOS (
	COD_EQUIPAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    STATUS_EQUIPAMENTO VARCHAR(20),
    DESCRICAO TEXT,
    NUMERO_SERIE VARCHAR(50) UNIQUE NOT NULL,
    PRECO_DIARIA DECIMAL(10,2) NOT NULL
);

CREATE TABLE ITEMRESERVA (
	COD_ITEM_RESERVA INT PRIMARY KEY AUTO_INCREMENT,
    QUANTIDADE INT DEFAULT 1,
    VALOR_DIARIA DECIMAL(10,2)
);

CREATE TABLE MANUTENCAO (
COD_MANUTENCAO INT PRIMARY KEY AUTO_INCREMENT,
RESPONSAVEL VARCHAR(100),
DATA_INICIO DATE NOT NULL,
DATA_FIM DATE,
DESCRICAO TEXT,
CUSTO DECIMAL (10,2)
);

CREATE TABLE FAZ (
	COD_FAZ INT PRIMARY KEY AUTO_INCREMENT,
    COD_MANUTENCAO INT NOT NULL,
    COD_EQUIPAMENTO INT NOT NULL,
    COD_ITEM_RESERVA INT NOT NULL,
    FOREIGN KEY (COD_MANUTENCAO) REFERENCES MANUTENCAO (COD_MANUTENCAO),
    FOREIGN KEY (COD_EQUIPAMENTO) REFERENCES EQUIPAMENTOS (COD_EQUIPAMENTO),
    FOREIGN KEY (COD_ITEM_RESERVA) REFERENCES ITEMRESERVA (COD_ITEM_RESERVA)
);

CREATE TABLE TEM (
	COD_TEM INT PRIMARY KEY AUTO_INCREMENT,
    COD_ITEM_RESERVA INT NOT NULL,
    COD_RESERVA INT NOT NULL,
    FOREIGN KEY (COD_ITEM_RESERVA) REFERENCES ITEMRESERVA (COD_ITEM_RESERVA),
    FOREIGN KEY (COD_RESERVA) REFERENCES RESERVA (COD_RESERVA)

);

CREATE TABLE RELACIONA (
	COD_RELACIONA INT PRIMARY KEY AUTO_INCREMENT,
    COD_ITEM_RESERVA INT NOT NULL,
    COD_EQUIPAMENTO INT NOT NULL,
    FOREIGN KEY (COD_ITEM_RESERVA) REFERENCES ITEMRESERVA (COD_ITEM_RESERVA),
    FOREIGN KEY (COD_EQUIPAMENTO) REFERENCES EQUIPAMENTOs (COD_EQUIPAMENTO)
);